### ISSUE TITLE
Path to the testnet

### ISSUE THREAD

**Issue by steinerkelvin** [Kindelia/Kindelia#27]
- [x] Infra-code to deploy nodes
- [x] Log collection and measurement
- [x] Saving blocks to disk
- [x] Saving heaps to disk
- [x] #47 
- [x] hi-level API

.
- [ ] Restoring heaps from disk
  - [x] Error handling on parser etc
- [x] Config file (initial peers etc)?
- [x] Fix re-deploy of functions?

...

Other stuff:
- [x] Interface to test (dry-run) transactions
  - [ ] Multiple-transaction `draw`?
- [ ] "proc" file
- [ ] IPv6? should? must?
- [ ] minimal CLI to interact with the file and UDP interfaces

**Comment by VictorTaelin** [comment]
Error handling parser isn't mandatory (it only happens when you first start the process), but is healthy.

File interface to publish transactions is needed.

IPv6 but not on first version.

Why multiple-transaction `draw`?

CLI should be minimal.

We also need a way to save / load blocks to disk, as well as heap snapshots (perhaps they could be mmapped?). Right now, whenever we restart the node, we lose all the work done.

**Comment by quleuber** [comment]
> File interface to publish transactions is needed.

This implies the parser handling the errors. Otherwise, the node will crash if someone tries to publish invalid code.

> Why multiple-transaction draw?

If I want to dry-run / test an entire file, the node has to be able to compute a new state with all transactions/statements and then drop them all. Do we already have some way to do this that I'm missing?

> perhaps they could be mmapped

This seems plausible, and efficient.

**Comment by VictorTaelin** [comment]
> If I want to dry-run / test an entire file, the node has to be able to compute a new state with all transactions/statements and then drop them all. Do we already have some way to do this that I'm missing?

In what scenario we need to dry-run / test an entire file?

> This implies the parser handling the errors. Otherwise, the node will crash if someone tries to publish invalid code.

That is what I just said, the file is only read when the program starts running, so if it crashes the program will just not launch. Not saying this is a good interface but parse errors aren't technically necessary to launch the test net. Keep in mind parse errors will be seen on Kind2, so Kindelia just deals with generated, correct files.
